In [1]:
!pip install numpy
!pip install pandas
!pip install sklearn
!pip install matplotlib

  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'


  error: subprocess-exited-with-error
  
  Getting requirements to build wheel did not run successfully.
  exit code: 1
  
  [15 lines of output]
  The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
  rather than 'sklearn' for pip commands.
  
  Here is how to fix this error in the main use cases:
  - use 'pip install scikit-learn' rather than 'pip install sklearn'
  - replace 'sklearn' by 'scikit-learn' in your pip requirements files
    (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
  - if the 'sklearn' package is used by one of your dependencies,
    it would be great if you take some time to track which package uses
    'sklearn' instead of 'scikit-learn' and report it to their issue tracker
  - as a last resort, set the environment variable
    SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
  
  More information is available at
  https://github.com/scikit-learn/sklearn-pypi-package
  [end of output]
  
  note: This error originates f

     ---------------------------------------- 0.0/165.5 kB ? eta -:--:--
     ------------------- ------------------- 81.9/165.5 kB 2.2 MB/s eta 0:00:01
     -------------------------------------- 165.5/165.5 kB 2.5 MB/s eta 0:00:00
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---- ----------------------------------- 0.8/8.0 MB 17.6 MB/s eta 0:00:01
   --------- ------------------------------ 1.8/8.0 MB 19.5 MB/s eta 0:00:01
   -------------- ------------------------- 2.9/8.0 MB 20.8 MB/s eta 0:00:01
   -------------------- ------------------- 4.1/8.0 MB 22.1 MB/s eta 0:00:01
   -------------------------- ------------- 5.3/8.0 MB 22.8 MB/s eta 0:00:01
   ------------------------------ --------- 6.0/8.0 MB 21.4 MB/s eta 0:00:01
   ------------------------------------ --- 7.2/8.0 MB 22.1 MB/s eta 0:00:01
   ---------------------------------------  8.0/8.0 MB 22.2 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 19.6 MB/s eta 0:00:00
   --

In [2]:
import pandas

In [5]:
import numpy

In [6]:
import numpy as rp

In [7]:
lista = [1, 2, 3, 4, 5, 6]
array = np.array(lista)

NameError: name 'np' is not defined

In [9]:
import numpy as np

In [10]:
lista = [1, 2, 3, 4, 5, 6]
array = np.array(lista)

In [15]:
print(type (lista))
print(type (array))

<class 'list'>
<class 'numpy.ndarray'>


In [16]:
arr_zeros = np.zeros(10)
print(arr_zeros)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [21]:
array[0] = 9
print(array)

[9 2 3 4 5 6]


In [22]:
## Matrizes
matriz_zeros = np.zeros ((5, 3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
## Notas de alunos
lista_de_notas = [9.8, 5.6, 7.8, 9.1, 6.5]
notas = np.array(lista_de_notas)

In [25]:
print('Maximo', notas.max())
print('Mínimo', notas.min())
print('Desvio padrão', notas.'())
print('Media', notas.mean())
print('Posição menor', notas.argmin())
print('Posição maior', notas.argmax())

Maximo 9.8
Mínimo 5.6
Desvio padrão 1.5628179676469045
Media 7.76
Posição menor 1
Posição maior 0
